name: TestitApiClient
targets:
  TestitApiClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sources]
    info:
      path: ./Info.plist
      version: v2.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
