//
// AIServiceModelApiResultGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AIServiceModelApiResultGroup: Codable, JSONEncodable, Hashable {

    public var key: GroupKey
    public var data: [AIServiceModelApiResult]
    public var totalCount: Int

    public init(key: GroupKey, data: [AIServiceModelApiResult], totalCount: Int) {
        self.key = key
        self.data = data
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case data
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(data, forKey: .data)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

