//
// AutoTestWorkItemIdentifierApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTestWorkItemIdentifierApiResult: Codable, JSONEncodable, Hashable {

    /** WorkItem unique internal identifier */
    public var id: UUID
    /** WorkItem Global unique identifier */
    public var globalId: Int64

    public init(id: UUID, globalId: Int64) {
        self.id = id
        self.globalId = globalId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case globalId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(globalId, forKey: .globalId)
    }
}

