//
// AutoTestNamespacesCountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTestNamespacesCountResponse: Codable, JSONEncodable, Hashable {

    public var namespaces: [AutoTestNamespaceCountApiModel]

    public init(namespaces: [AutoTestNamespaceCountApiModel]) {
        self.namespaces = namespaces
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespaces
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(namespaces, forKey: .namespaces)
    }
}

