//
// AutoTestResultReasonsCountItemModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTestResultReasonsCountItemModel: Codable, JSONEncodable, Hashable {

    public var failureCategory: AvailableFailureCategory
    public var count: Int

    public init(failureCategory: AvailableFailureCategory, count: Int) {
        self.failureCategory = failureCategory
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case failureCategory
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(failureCategory, forKey: .failureCategory)
        try container.encode(count, forKey: .count)
    }
}

