//
// AutoTestBulkDeleteApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTestBulkDeleteApiModel: Codable, JSONEncodable, Hashable {

    public var autoTestSelect: AutoTestSelectModel

    public init(autoTestSelect: AutoTestSelectModel) {
        self.autoTestSelect = autoTestSelect
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case autoTestSelect
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(autoTestSelect, forKey: .autoTestSelect)
    }
}

