//
// AutoTestAverageDurationModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTestAverageDurationModel: Codable, JSONEncodable, Hashable {

    public var passedAverageDuration: Double
    public var failedAverageDuration: Double

    public init(passedAverageDuration: Double, failedAverageDuration: Double) {
        self.passedAverageDuration = passedAverageDuration
        self.failedAverageDuration = failedAverageDuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case passedAverageDuration
        case failedAverageDuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(passedAverageDuration, forKey: .passedAverageDuration)
        try container.encode(failedAverageDuration, forKey: .failedAverageDuration)
    }
}

