//
// AutoTestProjectSettingsApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoTestProjectSettingsApiResult: Codable, JSONEncodable, Hashable {

    /** Unique ID of the project. */
    public var projectId: UUID
    /** Indicates if the status \"Flaky/Stable\" sets automatically */
    public var isFlakyAuto: Bool
    /** Stability percentage for autotest flaky computing */
    public var flakyStabilityPercentage: Int
    /** Last test run count for autotest flaky computing */
    public var flakyTestRunCount: Int
    /** Auto rerun enabled */
    public var rerunEnabled: Bool
    /** Auto rerun attempt count */
    public var rerunAttemptsCount: Int

    public init(projectId: UUID, isFlakyAuto: Bool, flakyStabilityPercentage: Int, flakyTestRunCount: Int, rerunEnabled: Bool, rerunAttemptsCount: Int) {
        self.projectId = projectId
        self.isFlakyAuto = isFlakyAuto
        self.flakyStabilityPercentage = flakyStabilityPercentage
        self.flakyTestRunCount = flakyTestRunCount
        self.rerunEnabled = rerunEnabled
        self.rerunAttemptsCount = rerunAttemptsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId
        case isFlakyAuto
        case flakyStabilityPercentage
        case flakyTestRunCount
        case rerunEnabled
        case rerunAttemptsCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(isFlakyAuto, forKey: .isFlakyAuto)
        try container.encode(flakyStabilityPercentage, forKey: .flakyStabilityPercentage)
        try container.encode(flakyTestRunCount, forKey: .flakyTestRunCount)
        try container.encode(rerunEnabled, forKey: .rerunEnabled)
        try container.encode(rerunAttemptsCount, forKey: .rerunAttemptsCount)
    }
}

