//
// BackgroundJobAttachmentModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BackgroundJobAttachmentModel: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var name: String
    public var type: String
    public var size: Float

    public init(id: UUID, name: String, type: String, size: Float) {
        self.id = id
        self.name = name
        self.type = type
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case type
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encode(size, forKey: .size)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension BackgroundJobAttachmentModel: Identifiable {}
