//
// CompositeFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CompositeFilter: Codable, JSONEncodable, Hashable {

    public var filters: [AnyCodable]
    public var _operator: LogicalOperator

    public init(filters: [AnyCodable], _operator: LogicalOperator) {
        self.filters = filters
        self._operator = _operator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filters
        case _operator = "operator"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filters, forKey: .filters)
        try container.encode(_operator, forKey: ._operator)
    }
}

