//
// CreateProjectFailureCategoryApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateProjectFailureCategoryApiModel: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Failure category name */
    public var name: String
    /** Category type */
    public var failureCategory: FailureCategory
    /** Failure category regexes */
    public var failureClassRegexes: [CreateFailureClassRegexApiModel]?

    public init(name: String, failureCategory: FailureCategory, failureClassRegexes: [CreateFailureClassRegexApiModel]? = nil) {
        self.name = name
        self.failureCategory = failureCategory
        self.failureClassRegexes = failureClassRegexes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case failureCategory
        case failureClassRegexes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(failureCategory, forKey: .failureCategory)
        try container.encodeIfPresent(failureClassRegexes, forKey: .failureClassRegexes)
    }
}

