//
// CustomAttributeTemplatePostModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomAttributeTemplatePostModel: Codable, JSONEncodable, Hashable {

    public static let customAttributeIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    public static let nameRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    /** Collection of attribute IDs */
    public var customAttributeIds: Set<UUID>?
    /** Custom attributes template name */
    public var name: String

    public init(customAttributeIds: Set<UUID>? = nil, name: String) {
        self.customAttributeIds = customAttributeIds
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customAttributeIds
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customAttributeIds, forKey: .customAttributeIds)
        try container.encode(name, forKey: .name)
    }
}

