//
// CustomAttributeOptionApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomAttributeOptionApiResult: Codable, JSONEncodable, Hashable {

    /** Unique ID of the attribute option */
    public var id: UUID
    /** Indicates if the attributes option is deleted */
    public var isDeleted: Bool
    /** Value of the attribute option */
    public var value: String?
    /** Indicates if the attribute option is used by default */
    public var isDefault: Bool

    public init(id: UUID, isDeleted: Bool, value: String? = nil, isDefault: Bool) {
        self.id = id
        self.isDeleted = isDeleted
        self.value = value
        self.isDefault = isDefault
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case isDeleted
        case value
        case isDefault
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encode(isDefault, forKey: .isDefault)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CustomAttributeOptionApiResult: Identifiable {}
