//
// ExternalFormCreateModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExternalFormCreateModel: Codable, JSONEncodable, Hashable {

    public var possibleValues: [String: [ExternalFormAllowedValueModel]]
    public var fields: [ExternalFormFieldModel]
    public var links: [ExternalFormLinkModel]
    public var values: [String: AnyCodable]

    public init(possibleValues: [String: [ExternalFormAllowedValueModel]], fields: [ExternalFormFieldModel], links: [ExternalFormLinkModel], values: [String: AnyCodable]) {
        self.possibleValues = possibleValues
        self.fields = fields
        self.links = links
        self.values = values
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case possibleValues
        case fields
        case links
        case values
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(possibleValues, forKey: .possibleValues)
        try container.encode(fields, forKey: .fields)
        try container.encode(links, forKey: .links)
        try container.encode(values, forKey: .values)
    }
}

