//
// ExternalIssueApiFieldSuggestionGroupedReply.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExternalIssueApiFieldSuggestionGroupedReply: Codable, JSONEncodable, Hashable {

    public var groups: [ExternalIssueApiFieldSuggestionGroup]
    public var totalCount: Int

    public init(groups: [ExternalIssueApiFieldSuggestionGroup], totalCount: Int) {
        self.groups = groups
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groups
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(groups, forKey: .groups)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

