//
// ExternalFormModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExternalFormModel: Codable, JSONEncodable, Hashable {

    public var fields: [ExternalFormFieldModel]
    public var possibleValues: [String: [ExternalFormAllowedValueModel]]

    public init(fields: [ExternalFormFieldModel], possibleValues: [String: [ExternalFormAllowedValueModel]]) {
        self.fields = fields
        self.possibleValues = possibleValues
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fields
        case possibleValues
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fields, forKey: .fields)
        try container.encode(possibleValues, forKey: .possibleValues)
    }
}

