//
// ExternalServiceMetadataApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExternalServiceMetadataApiResult: Codable, JSONEncodable, Hashable {

    /** The name of the external service */
    public var name: String
    /** The code of the external service */
    public var code: String
    /** The icon URL of the external service */
    public var iconUrl: String
    /** The category of the external service */
    public var category: ExternalServiceCategoryApiResult

    public init(name: String, code: String, iconUrl: String, category: ExternalServiceCategoryApiResult) {
        self.name = name
        self.code = code
        self.iconUrl = iconUrl
        self.category = category
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case code
        case iconUrl
        case category
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(code, forKey: .code)
        try container.encode(iconUrl, forKey: .iconUrl)
        try container.encode(category, forKey: .category)
    }
}

