//
// FailureCategoryGroupSearchApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FailureCategoryGroupSearchApiModel: Codable, JSONEncodable, Hashable {

    /** Inquiry details */
    public var inquiry: Inquiry
    /** Group details */
    public var group: FailureCategoryGroupApiModel?

    public init(inquiry: Inquiry, group: FailureCategoryGroupApiModel? = nil) {
        self.inquiry = inquiry
        self.group = group
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inquiry
        case group
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(inquiry, forKey: .inquiry)
        try container.encodeIfPresent(group, forKey: .group)
    }
}

