//
// GetExternalFormApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetExternalFormApiResult: Codable, JSONEncodable, Hashable {

    /** Linked test result IDs */
    public var testResultIds: [UUID]
    /** External form definition */
    public var form: ExternalFormModel

    public init(testResultIds: [UUID], form: ExternalFormModel) {
        self.testResultIds = testResultIds
        self.form = form
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case testResultIds
        case form
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(testResultIds, forKey: .testResultIds)
        try container.encode(form, forKey: .form)
    }
}

