//
// GetShortProjectsApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetShortProjectsApiModel: Codable, JSONEncodable, Hashable {

    public var inquiry: Inquiry?
    public var permissionName: String?
    public var permissionType: String?

    public init(inquiry: Inquiry? = nil, permissionName: String? = nil, permissionType: String? = nil) {
        self.inquiry = inquiry
        self.permissionName = permissionName
        self.permissionType = permissionType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inquiry
        case permissionName
        case permissionType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inquiry, forKey: .inquiry)
        try container.encodeIfPresent(permissionName, forKey: .permissionName)
        try container.encodeIfPresent(permissionType, forKey: .permissionType)
    }
}

