//
// GlobalSearchItemResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalSearchItemResult: Codable, JSONEncodable, Hashable {

    public var resourceType: String
    public var resourceId: UUID
    public var globalId: Int64?
    public var name: String
    public var projectGlobalId: Int64

    public init(resourceType: String, resourceId: UUID, globalId: Int64? = nil, name: String, projectGlobalId: Int64) {
        self.resourceType = resourceType
        self.resourceId = resourceId
        self.globalId = globalId
        self.name = name
        self.projectGlobalId = projectGlobalId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resourceType
        case resourceId
        case globalId
        case name
        case projectGlobalId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(resourceType, forKey: .resourceType)
        try container.encode(resourceId, forKey: .resourceId)
        try container.encodeIfPresent(globalId, forKey: .globalId)
        try container.encode(name, forKey: .name)
        try container.encode(projectGlobalId, forKey: .projectGlobalId)
    }
}

