//
// GlobalSearchRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GlobalSearchRequest: Codable, JSONEncodable, Hashable {

    public var query: String
    public var resourceType: String?
    public var take: Int
    public var skip: Int

    public init(query: String, resourceType: String? = nil, take: Int, skip: Int) {
        self.query = query
        self.resourceType = resourceType
        self.take = take
        self.skip = skip
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
        case resourceType
        case take
        case skip
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(query, forKey: .query)
        try container.encodeIfPresent(resourceType, forKey: .resourceType)
        try container.encode(take, forKey: .take)
        try container.encode(skip, forKey: .skip)
    }
}

