//
// ManualRerunSelectTestResultsApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ManualRerunSelectTestResultsApiModel: Codable, JSONEncodable, Hashable {

    public var filter: TestResultsFilterApiModel?
    public var extractionModel: ManualRerunTestResultApiModel?

    public init(filter: TestResultsFilterApiModel? = nil, extractionModel: ManualRerunTestResultApiModel? = nil) {
        self.filter = filter
        self.extractionModel = extractionModel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case extractionModel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filter, forKey: .filter)
        try container.encodeIfPresent(extractionModel, forKey: .extractionModel)
    }
}

