//
// Mode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Mode: String, Codable, CaseIterable {
    case countOnly = "CountOnly"
    case all = "All"
}
