//
// ParameterGroupModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ParameterGroupModel: Codable, JSONEncodable, Hashable {

    public var name: String
    public var values: [String: String]
    public var parameterKeyId: UUID

    public init(name: String, values: [String: String], parameterKeyId: UUID) {
        self.name = name
        self.values = values
        self.parameterKeyId = parameterKeyId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case values
        case parameterKeyId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(values, forKey: .values)
        try container.encode(parameterKeyId, forKey: .parameterKeyId)
    }
}

