//
// ProjectShortApiResultIReply.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ProjectShortApiResultIReply: Codable, JSONEncodable, Hashable {
    case typeProjectShortApiResultGroupedReply(ProjectShortApiResultGroupedReply)
    case typeProjectShortApiResultReply(ProjectShortApiResultReply)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeProjectShortApiResultGroupedReply(let value):
            try container.encode(value)
        case .typeProjectShortApiResultReply(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(ProjectShortApiResultGroupedReply.self) {
            self = .typeProjectShortApiResultGroupedReply(value)
        } else if let value = try? container.decode(ProjectShortApiResultReply.self) {
            self = .typeProjectShortApiResultReply(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ProjectShortApiResultIReply"))
        }
    }
}

