//
// ProjectFailureCategoryApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProjectFailureCategoryApiResult: Codable, JSONEncodable, Hashable {

    /** Failure category identifier */
    public var id: UUID
    /** Failure category name */
    public var name: String?
    /** Category type */
    public var failureCategory: FailureCategory
    /** Failure category creation date */
    public var createdDate: Date
    /** Failure category creator identifier */
    public var createdById: UUID
    /** Failure category last modification date */
    public var modifiedDate: Date?
    /** Failure category last modifier identifier */
    public var modifiedById: UUID?
    /** Projects relations count */
    public var projectsCount: Int
    /** Category type index */
    public var failureCategoryId: Int
    /** Regexes count */
    public var regexCount: Int

    public init(id: UUID, name: String? = nil, failureCategory: FailureCategory, createdDate: Date, createdById: UUID, modifiedDate: Date? = nil, modifiedById: UUID? = nil, projectsCount: Int, failureCategoryId: Int, regexCount: Int) {
        self.id = id
        self.name = name
        self.failureCategory = failureCategory
        self.createdDate = createdDate
        self.createdById = createdById
        self.modifiedDate = modifiedDate
        self.modifiedById = modifiedById
        self.projectsCount = projectsCount
        self.failureCategoryId = failureCategoryId
        self.regexCount = regexCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case failureCategory
        case createdDate
        case createdById
        case modifiedDate
        case modifiedById
        case projectsCount
        case failureCategoryId
        case regexCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(failureCategory, forKey: .failureCategory)
        try container.encode(createdDate, forKey: .createdDate)
        try container.encode(createdById, forKey: .createdById)
        try container.encodeIfPresent(modifiedDate, forKey: .modifiedDate)
        try container.encodeIfPresent(modifiedById, forKey: .modifiedById)
        try container.encode(projectsCount, forKey: .projectsCount)
        try container.encode(failureCategoryId, forKey: .failureCategoryId)
        try container.encode(regexCount, forKey: .regexCount)
    }
}

