//
// ProjectType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ProjectType: String, Codable, CaseIterable {
    case regular = "Regular"
    case demo = "Demo"
}
