//
// RerunTestResultModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RerunTestResultModel: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var outcome: String?
    public var runNumber: Int

    public init(id: UUID, outcome: String? = nil, runNumber: Int) {
        self.id = id
        self.outcome = outcome
        self.runNumber = runNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case outcome
        case runNumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(outcome, forKey: .outcome)
        try container.encode(runNumber, forKey: .runNumber)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RerunTestResultModel: Identifiable {}
