//
// RoleApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RoleApiModel: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var name: String
    public var isSystem: Bool

    public init(id: UUID, name: String, isSystem: Bool) {
        self.id = id
        self.name = name
        self.isSystem = isSystem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case isSystem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(isSystem, forKey: .isSystem)
    }
}

