//
// ScheduleAutoTestsReportImportsApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScheduleAutoTestsReportImportsApiModel: Codable, JSONEncodable, Hashable {

    static let reportsRule = ArrayRule(minItems: 1, maxItems: nil, uniqueItems: false)
    /** Collection of reports to import. */
    public var reports: [ScheduleAutoTestsReportImportApiModel]

    public init(reports: [ScheduleAutoTestsReportImportApiModel]) {
        self.reports = reports
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reports
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reports, forKey: .reports)
    }
}

