//
// SearchAutoTestsQueryIncludesModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchAutoTestsQueryIncludesModel: Codable, JSONEncodable, Hashable {

    /** If autotest steps will be included */
    public var includeSteps: Bool
    /** If autotest links will be included */
    public var includeLinks: Bool
    /** If autotest labels will be included */
    public var includeLabels: Bool

    public init(includeSteps: Bool, includeLinks: Bool, includeLabels: Bool) {
        self.includeSteps = includeSteps
        self.includeLinks = includeLinks
        self.includeLabels = includeLabels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case includeSteps
        case includeLinks
        case includeLabels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(includeSteps, forKey: .includeSteps)
        try container.encode(includeLinks, forKey: .includeLinks)
        try container.encode(includeLabels, forKey: .includeLabels)
    }
}

