//
// SharedStepReferenceSectionModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SharedStepReferenceSectionModel: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var name: String
    public var hasThisSharedStepAsPrecondition: Bool
    public var hasThisSharedStepAsPostcondition: Bool
    public var createdById: UUID
    public var modifiedById: UUID?
    public var createdDate: Date?
    public var modifiedDate: Date?
    public var isDeleted: Bool

    public init(id: UUID, name: String, hasThisSharedStepAsPrecondition: Bool, hasThisSharedStepAsPostcondition: Bool, createdById: UUID, modifiedById: UUID? = nil, createdDate: Date? = nil, modifiedDate: Date? = nil, isDeleted: Bool) {
        self.id = id
        self.name = name
        self.hasThisSharedStepAsPrecondition = hasThisSharedStepAsPrecondition
        self.hasThisSharedStepAsPostcondition = hasThisSharedStepAsPostcondition
        self.createdById = createdById
        self.modifiedById = modifiedById
        self.createdDate = createdDate
        self.modifiedDate = modifiedDate
        self.isDeleted = isDeleted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case hasThisSharedStepAsPrecondition
        case hasThisSharedStepAsPostcondition
        case createdById
        case modifiedById
        case createdDate
        case modifiedDate
        case isDeleted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(hasThisSharedStepAsPrecondition, forKey: .hasThisSharedStepAsPrecondition)
        try container.encode(hasThisSharedStepAsPostcondition, forKey: .hasThisSharedStepAsPostcondition)
        try container.encode(createdById, forKey: .createdById)
        try container.encodeIfPresent(modifiedById, forKey: .modifiedById)
        try container.encodeIfPresent(createdDate, forKey: .createdDate)
        try container.encodeIfPresent(modifiedDate, forKey: .modifiedDate)
        try container.encode(isDeleted, forKey: .isDeleted)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SharedStepReferenceSectionModel: Identifiable {}
