//
// TestPlanChangedFieldsViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestPlanChangedFieldsViewModel: Codable, JSONEncodable, Hashable {

    public var name: StringChangedFieldWithDiffsViewModel?
    public var description: StringChangedFieldWithDiffsViewModel?
    public var productName: StringChangedFieldWithDiffsViewModel?
    public var build: StringChangedFieldWithDiffsViewModel?
    public var period: PeriodViewModelChangedFieldViewModel?
    public var status: StringChangedFieldWithDiffsViewModel?
    public var tags: StringArrayChangedFieldViewModel?
    public var testSuite: TestSuiteChangeViewModelChangedFieldViewModel?
    public var testPoints: TestPointChangeViewModelChangedFieldViewModel?
    public var testResults: TestResultChangeViewModelChangedFieldViewModel?
    public var locking: BooleanChangedFieldViewModel?
    public var hasAutomaticDurationTimer: BooleanNullableChangedFieldViewModel?
    public var attributes: [String: CustomAttributeChangeModel]?

    public init(name: StringChangedFieldWithDiffsViewModel? = nil, description: StringChangedFieldWithDiffsViewModel? = nil, productName: StringChangedFieldWithDiffsViewModel? = nil, build: StringChangedFieldWithDiffsViewModel? = nil, period: PeriodViewModelChangedFieldViewModel? = nil, status: StringChangedFieldWithDiffsViewModel? = nil, tags: StringArrayChangedFieldViewModel? = nil, testSuite: TestSuiteChangeViewModelChangedFieldViewModel? = nil, testPoints: TestPointChangeViewModelChangedFieldViewModel? = nil, testResults: TestResultChangeViewModelChangedFieldViewModel? = nil, locking: BooleanChangedFieldViewModel? = nil, hasAutomaticDurationTimer: BooleanNullableChangedFieldViewModel? = nil, attributes: [String: CustomAttributeChangeModel]? = nil) {
        self.name = name
        self.description = description
        self.productName = productName
        self.build = build
        self.period = period
        self.status = status
        self.tags = tags
        self.testSuite = testSuite
        self.testPoints = testPoints
        self.testResults = testResults
        self.locking = locking
        self.hasAutomaticDurationTimer = hasAutomaticDurationTimer
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case productName
        case build
        case period
        case status
        case tags
        case testSuite
        case testPoints
        case testResults
        case locking
        case hasAutomaticDurationTimer
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(productName, forKey: .productName)
        try container.encodeIfPresent(build, forKey: .build)
        try container.encodeIfPresent(period, forKey: .period)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(testSuite, forKey: .testSuite)
        try container.encodeIfPresent(testPoints, forKey: .testPoints)
        try container.encodeIfPresent(testResults, forKey: .testResults)
        try container.encodeIfPresent(locking, forKey: .locking)
        try container.encodeIfPresent(hasAutomaticDurationTimer, forKey: .hasAutomaticDurationTimer)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

