//
// TestPlanTestPointsSectionSearchApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestPlanTestPointsSectionSearchApiResult: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var orderRank: String
    public var name: String?

    public init(id: UUID, orderRank: String, name: String? = nil) {
        self.id = id
        self.orderRank = orderRank
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case orderRank
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(orderRank, forKey: .orderRank)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

