//
// TestPlanTestPointsGroupApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestPlanTestPointsGroupApiResult: Codable, JSONEncodable, Hashable {

    public var fieldValue: AnyCodable?
    public var displayFieldValue: AnyCodable?
    public var count: Int

    public init(fieldValue: AnyCodable?, displayFieldValue: AnyCodable?, count: Int) {
        self.fieldValue = fieldValue
        self.displayFieldValue = displayFieldValue
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fieldValue
        case displayFieldValue
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fieldValue, forKey: .fieldValue)
        try container.encode(displayFieldValue, forKey: .displayFieldValue)
        try container.encode(count, forKey: .count)
    }
}

