//
// TestSuiteChangeViewModelChangedFieldViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestSuiteChangeViewModelChangedFieldViewModel: Codable, JSONEncodable, Hashable {

    public var oldValue: TestSuiteChangeViewModel?
    public var newValue: TestSuiteChangeViewModel?

    public init(oldValue: TestSuiteChangeViewModel? = nil, newValue: TestSuiteChangeViewModel? = nil) {
        self.oldValue = oldValue
        self.newValue = newValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case oldValue
        case newValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(oldValue, forKey: .oldValue)
        try container.encodeIfPresent(newValue, forKey: .newValue)
    }
}

