//
// TestPlanTestPointsAutoTestsRunApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestPlanTestPointsAutoTestsRunApiModel: Codable, JSONEncodable, Hashable {

    /** Test points filters. */
    public var filter: TestPlanTestPointsSearchApiModel?
    /** Test points extraction model. */
    public var extractionModel: TestPlanTestPointsExtractionApiModel?
    /** Webhook ids to run. */
    public var webhookIds: [UUID]
    /** Specifies the test run build. */
    public var build: String?
    /** Reset test point status when actual work item does not automated. */
    public var resetNotActualAutomatedTestPoints: Bool
    /** Tags of the test run. */
    public var tags: [String]?

    public init(filter: TestPlanTestPointsSearchApiModel? = nil, extractionModel: TestPlanTestPointsExtractionApiModel? = nil, webhookIds: [UUID], build: String? = nil, resetNotActualAutomatedTestPoints: Bool, tags: [String]? = nil) {
        self.filter = filter
        self.extractionModel = extractionModel
        self.webhookIds = webhookIds
        self.build = build
        self.resetNotActualAutomatedTestPoints = resetNotActualAutomatedTestPoints
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case extractionModel
        case webhookIds
        case build
        case resetNotActualAutomatedTestPoints
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filter, forKey: .filter)
        try container.encodeIfPresent(extractionModel, forKey: .extractionModel)
        try container.encode(webhookIds, forKey: .webhookIds)
        try container.encodeIfPresent(build, forKey: .build)
        try container.encode(resetNotActualAutomatedTestPoints, forKey: .resetNotActualAutomatedTestPoints)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

