//
// TestPlanTestPointsGroupSearchItemApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestPlanTestPointsGroupSearchItemApiResult: Codable, JSONEncodable, Hashable {

    public var group: TestPlanTestPointsGroupApiResult?
    public var items: [TestPlanTestPointsSearchApiResult]

    public init(group: TestPlanTestPointsGroupApiResult?, items: [TestPlanTestPointsSearchApiResult]) {
        self.group = group
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case group
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(group, forKey: .group)
        try container.encode(items, forKey: .items)
    }
}

