//
// TestPlanTestPointsInquiryApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestPlanTestPointsInquiryApiModel: Codable, JSONEncodable, Hashable {

    public var order: [Order]
    public var page: Page?

    public init(order: [Order], page: Page? = nil) {
        self.order = order
        self.page = page
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case order
        case page
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(order, forKey: .order)
        try container.encodeIfPresent(page, forKey: .page)
    }
}

