//
// TestPlanStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum TestPlanStatus: String, Codable, CaseIterable {
    case new = "New"
    case inProgress = "InProgress"
    case paused = "Paused"
    case completed = "Completed"
}
