//
// TestPlanGroupByStatusCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestPlanGroupByStatusCode: Codable, JSONEncodable, Hashable {

    public var statusCode: String
    public var value: Int64

    public init(statusCode: String, value: Int64) {
        self.statusCode = statusCode
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case statusCode
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(statusCode, forKey: .statusCode)
        try container.encode(value, forKey: .value)
    }
}

