//
// TestRunLaunchOptionApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestRunLaunchOptionApiModel: Codable, JSONEncodable, Hashable {

    /** Customers test run parameters. */
    public var customParameters: [String: String]?
    /** Enabled webhooks. */
    public var webhookIds: [UUID]

    public init(customParameters: [String: String]? = nil, webhookIds: [UUID]) {
        self.customParameters = customParameters
        self.webhookIds = webhookIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customParameters
        case webhookIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customParameters, forKey: .customParameters)
        try container.encode(webhookIds, forKey: .webhookIds)
    }
}

