//
// TestRunV2PutModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestRunV2PutModel: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: UUID
    public var name: String
    public var description: String?
    /** Once launch source is specified it cannot be updated */
    public var launchSource: String?
    public var attachments: [AttachmentPutModel]?
    public var links: [LinkPutModel]?

    public init(id: UUID, name: String, description: String? = nil, launchSource: String? = nil, attachments: [AttachmentPutModel]? = nil, links: [LinkPutModel]? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.launchSource = launchSource
        self.attachments = attachments
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case launchSource
        case attachments
        case links
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(launchSource, forKey: .launchSource)
        try container.encodeIfPresent(attachments, forKey: .attachments)
        try container.encodeIfPresent(links, forKey: .links)
    }
}

