//
// TestRunGroupByFailureClassModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestRunGroupByFailureClassModel: Codable, JSONEncodable, Hashable {

    public var failureCategory: String
    public var value: Int

    public init(failureCategory: String, value: Int) {
        self.failureCategory = failureCategory
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case failureCategory
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(failureCategory, forKey: .failureCategory)
        try container.encode(value, forKey: .value)
    }
}

