//
// UpdateWorkflowApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateWorkflowApiModel: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    public var isDefault: Bool
    public var statuses: [WorkflowStatusApiModel]
    public var projectIds: [UUID]

    public init(name: String, isDefault: Bool, statuses: [WorkflowStatusApiModel], projectIds: [UUID]) {
        self.name = name
        self.isDefault = isDefault
        self.statuses = statuses
        self.projectIds = projectIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case isDefault
        case statuses
        case projectIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(isDefault, forKey: .isDefault)
        try container.encode(statuses, forKey: .statuses)
        try container.encode(projectIds, forKey: .projectIds)
    }
}

