//
// UpdateFailureClassRegexApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateFailureClassRegexApiModel: Codable, JSONEncodable, Hashable {

    public static let regexTextRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Regex unique identifier */
    public var id: UUID
    /** Regex value */
    public var regexText: String

    public init(id: UUID, regexText: String) {
        self.id = id
        self.regexText = regexText
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case regexText
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(regexText, forKey: .regexText)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UpdateFailureClassRegexApiModel: Identifiable {}
