//
// UpdateWorkItemApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateWorkItemApiModel: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    static let durationRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: 86400000, exclusiveMaximum: false, multipleOf: nil)
    /** Unique identifier of the work item */
    public var id: UUID
    /** Unique identifier of the section within a project */
    public var sectionId: UUID
    /** Name of the work item */
    public var name: String
    /** Description of the work item */
    public var description: String?
    /** Duration of the work item in milliseconds */
    public var duration: Int64
    /** Current state of the work item */
    public var state: WorkItemStateApiModel
    /** Priority level assigned to the work item */
    public var priority: WorkItemPriorityApiModel
    /** Set of custom attributes associated with the work item */
    public var attributes: [String: AnyCodable]?
    /** Set of tags applied to the work item */
    public var tags: [TagModel]?
    /** Set of precondition steps that must be executed before the main steps */
    public var preconditionSteps: [UpdateStepApiModel]?
    /** Set of main steps or actions defined for the work item */
    public var steps: [UpdateStepApiModel]?
    /** Set of postcondition steps that are executed after completing the main steps */
    public var postconditionSteps: [UpdateStepApiModel]?
    /** Set of iterations associated with the work item */
    public var iterations: [AssignIterationApiModel]?
    /** Set of automated tests linked to the work item */
    public var autoTests: [AutoTestIdModel]?
    /** Set of files attached to the work item */
    public var attachments: [AssignAttachmentApiModel]?
    /** Set of links related to the work item */
    public var links: [UpdateLinkApiModel]?
    /** Set of parameter keys associated with the work item */
    public var parameters: [WorkItemParameterKeyApiModel]?

    public init(id: UUID, sectionId: UUID, name: String, description: String? = nil, duration: Int64, state: WorkItemStateApiModel, priority: WorkItemPriorityApiModel, attributes: [String: AnyCodable]? = nil, tags: [TagModel]? = nil, preconditionSteps: [UpdateStepApiModel]? = nil, steps: [UpdateStepApiModel]? = nil, postconditionSteps: [UpdateStepApiModel]? = nil, iterations: [AssignIterationApiModel]? = nil, autoTests: [AutoTestIdModel]? = nil, attachments: [AssignAttachmentApiModel]? = nil, links: [UpdateLinkApiModel]? = nil, parameters: [WorkItemParameterKeyApiModel]? = nil) {
        self.id = id
        self.sectionId = sectionId
        self.name = name
        self.description = description
        self.duration = duration
        self.state = state
        self.priority = priority
        self.attributes = attributes
        self.tags = tags
        self.preconditionSteps = preconditionSteps
        self.steps = steps
        self.postconditionSteps = postconditionSteps
        self.iterations = iterations
        self.autoTests = autoTests
        self.attachments = attachments
        self.links = links
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case sectionId
        case name
        case description
        case duration
        case state
        case priority
        case attributes
        case tags
        case preconditionSteps
        case steps
        case postconditionSteps
        case iterations
        case autoTests
        case attachments
        case links
        case parameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(sectionId, forKey: .sectionId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(duration, forKey: .duration)
        try container.encode(state, forKey: .state)
        try container.encode(priority, forKey: .priority)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(preconditionSteps, forKey: .preconditionSteps)
        try container.encodeIfPresent(steps, forKey: .steps)
        try container.encodeIfPresent(postconditionSteps, forKey: .postconditionSteps)
        try container.encodeIfPresent(iterations, forKey: .iterations)
        try container.encodeIfPresent(autoTests, forKey: .autoTests)
        try container.encodeIfPresent(attachments, forKey: .attachments)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(parameters, forKey: .parameters)
    }
}

