//
// UpdateWorkItemCommentApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateWorkItemCommentApiModel: Codable, JSONEncodable, Hashable {

    static let textRule = StringRule(minLength: 1, maxLength: 1024, pattern: nil)
    /** ID of the comment */
    public var id: UUID
    /** Text of the comment */
    public var text: String

    public init(id: UUID, text: String) {
        self.id = id
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(text, forKey: .text)
    }
}

