//
// WebhooksUpdateApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebhooksUpdateApiModel: Codable, JSONEncodable, Hashable {

    public var filter: WebhooksFilterApiModel
    public var model: WebhookBulkUpdateApiModel
    public var extractor: WebhooksExtractionApiModel

    public init(filter: WebhooksFilterApiModel, model: WebhookBulkUpdateApiModel, extractor: WebhooksExtractionApiModel) {
        self.filter = filter
        self.model = model
        self.extractor = extractor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case model
        case extractor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filter, forKey: .filter)
        try container.encode(model, forKey: .model)
        try container.encode(extractor, forKey: .extractor)
    }
}

