//
// WebHookTestModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebHookTestModel: Codable, JSONEncodable, Hashable {

    static let urlRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Request method of the webhook */
    public var requestType: RequestTypeModel
    /** Request URL of the webhook */
    public var url: String

    public init(requestType: RequestTypeModel, url: String) {
        self.requestType = requestType
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestType
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestType, forKey: .requestType)
        try container.encode(url, forKey: .url)
    }
}

