//
// WorkflowStatusApiResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkflowStatusApiResult: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var name: String
    public var code: String
    /** Collection of possible status types */
    public var type: TestStatusApiType
    public var description: String?
    public var isSystem: Bool
    public var priority: Int

    public init(id: UUID, name: String, code: String, type: TestStatusApiType, description: String?, isSystem: Bool, priority: Int) {
        self.id = id
        self.name = name
        self.code = code
        self.type = type
        self.description = description
        self.isSystem = isSystem
        self.priority = priority
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case code
        case type
        case description
        case isSystem
        case priority
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(code, forKey: .code)
        try container.encode(type, forKey: .type)
        try container.encode(description, forKey: .description)
        try container.encode(isSystem, forKey: .isSystem)
        try container.encode(priority, forKey: .priority)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension WorkflowStatusApiResult: Identifiable {}
