//
// WorkItemStepChangeViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkItemStepChangeViewModel: Codable, JSONEncodable, Hashable {

    public var action: String
    public var expected: String
    public var comments: String
    public var testData: String
    public var index: Int
    public var workItemId: UUID?
    public var workItem: SharedStepChangeViewModel

    public init(action: String, expected: String, comments: String, testData: String, index: Int, workItemId: UUID? = nil, workItem: SharedStepChangeViewModel) {
        self.action = action
        self.expected = expected
        self.comments = comments
        self.testData = testData
        self.index = index
        self.workItemId = workItemId
        self.workItem = workItem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case expected
        case comments
        case testData
        case index
        case workItemId
        case workItem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(expected, forKey: .expected)
        try container.encode(comments, forKey: .comments)
        try container.encode(testData, forKey: .testData)
        try container.encode(index, forKey: .index)
        try container.encodeIfPresent(workItemId, forKey: .workItemId)
        try container.encode(workItem, forKey: .workItem)
    }
}

