//
// WorkItemCommentModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkItemCommentModel: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var text: String
    public var user: UserWithRankModel
    public var createdById: UUID
    public var modifiedById: UUID?
    public var createdDate: Date
    public var modifiedDate: Date?

    public init(id: UUID, text: String, user: UserWithRankModel, createdById: UUID, modifiedById: UUID? = nil, createdDate: Date, modifiedDate: Date? = nil) {
        self.id = id
        self.text = text
        self.user = user
        self.createdById = createdById
        self.modifiedById = modifiedById
        self.createdDate = createdDate
        self.modifiedDate = modifiedDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case text
        case user
        case createdById
        case modifiedById
        case createdDate
        case modifiedDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(text, forKey: .text)
        try container.encode(user, forKey: .user)
        try container.encode(createdById, forKey: .createdById)
        try container.encodeIfPresent(modifiedById, forKey: .modifiedById)
        try container.encode(createdDate, forKey: .createdDate)
        try container.encodeIfPresent(modifiedDate, forKey: .modifiedDate)
    }
}

