//
// WorkItemChangedAttributeViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkItemChangedAttributeViewModel: Codable, JSONEncodable, Hashable {

    public var type: String
    public var oldAttributeName: String
    public var newAttributeName: String
    public var oldValue: AnyCodable?
    public var newValue: AnyCodable?

    public init(type: String, oldAttributeName: String, newAttributeName: String, oldValue: AnyCodable?, newValue: AnyCodable?) {
        self.type = type
        self.oldAttributeName = oldAttributeName
        self.newAttributeName = newAttributeName
        self.oldValue = oldValue
        self.newValue = newValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case oldAttributeName
        case newAttributeName
        case oldValue
        case newValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(oldAttributeName, forKey: .oldAttributeName)
        try container.encode(newAttributeName, forKey: .newAttributeName)
        try container.encode(oldValue, forKey: .oldValue)
        try container.encode(newValue, forKey: .newValue)
    }
}

