//
// WorkItemExternalMetadataFilterApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkItemExternalMetadataFilterApiModel: Codable, JSONEncodable, Hashable {

    /** Identifiers of external issues to search for */
    public var ids: [WorkItemExternalMetadataFieldFilterApiModel]?
    /** Types of external issues to search for */
    public var types: [WorkItemExternalMetadataFieldFilterApiModel]?
    /** Priorities of external issues to search for */
    public var priorities: [WorkItemExternalMetadataFieldFilterApiModel]?
    /** Statuses of external issues to search for */
    public var statuses: [WorkItemExternalMetadataFieldFilterApiModel]?
    /** Assignees of external issues to search for */
    public var assignees: [WorkItemExternalMetadataFieldFilterApiModel]?

    public init(ids: [WorkItemExternalMetadataFieldFilterApiModel]? = nil, types: [WorkItemExternalMetadataFieldFilterApiModel]? = nil, priorities: [WorkItemExternalMetadataFieldFilterApiModel]? = nil, statuses: [WorkItemExternalMetadataFieldFilterApiModel]? = nil, assignees: [WorkItemExternalMetadataFieldFilterApiModel]? = nil) {
        self.ids = ids
        self.types = types
        self.priorities = priorities
        self.statuses = statuses
        self.assignees = assignees
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ids
        case types
        case priorities
        case statuses
        case assignees
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ids, forKey: .ids)
        try container.encodeIfPresent(types, forKey: .types)
        try container.encodeIfPresent(priorities, forKey: .priorities)
        try container.encodeIfPresent(statuses, forKey: .statuses)
        try container.encodeIfPresent(assignees, forKey: .assignees)
    }
}

