//
// WorkItemPriorityApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum WorkItemPriorityApiModel: String, Codable, CaseIterable {
    case lowest = "Lowest"
    case low = "Low"
    case medium = "Medium"
    case high = "High"
    case highest = "Highest"
}
