//
// WorkItemSourceTypeApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum WorkItemSourceTypeApiModel: String, Codable, CaseIterable {
    case manual = "Manual"
    case ai = "AI"
}
