//
// WorkItemLinkFilterApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkItemLinkFilterApiModel: Codable, JSONEncodable, Hashable {

    public static let typesRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    public static let urlsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    public var types: Set<LinkType>?
    public var title: String?
    public var urls: Set<String>?
    public var onlyWithoutLinks: Bool?

    public init(types: Set<LinkType>? = nil, title: String? = nil, urls: Set<String>? = nil, onlyWithoutLinks: Bool? = nil) {
        self.types = types
        self.title = title
        self.urls = urls
        self.onlyWithoutLinks = onlyWithoutLinks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case types
        case title
        case urls
        case onlyWithoutLinks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(types, forKey: .types)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(urls, forKey: .urls)
        try container.encodeIfPresent(onlyWithoutLinks, forKey: .onlyWithoutLinks)
    }
}

