//
// WorkItemUpdatingFieldsApiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WorkItemUpdatingFieldsApiModel: Codable, JSONEncodable, Hashable {

    /** Work item name updating enabled */
    public var name: Bool? = false
    /** Work item description updating enabled */
    public var description: Bool? = false
    /** Work item precondition steps updating enabled */
    public var preconditionSteps: Bool? = false
    /** Work item steps updating enabled */
    public var steps: Bool? = false
    /** Work item postcondition steps updating enabled */
    public var postconditionSteps: Bool? = false
    /** Work item links updating enabled */
    public var links: Bool? = false
    /** Work item tags updating enabled */
    public var tags: Bool? = false

    public init(name: Bool? = false, description: Bool? = false, preconditionSteps: Bool? = false, steps: Bool? = false, postconditionSteps: Bool? = false, links: Bool? = false, tags: Bool? = false) {
        self.name = name
        self.description = description
        self.preconditionSteps = preconditionSteps
        self.steps = steps
        self.postconditionSteps = postconditionSteps
        self.links = links
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case preconditionSteps
        case steps
        case postconditionSteps
        case links
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(preconditionSteps, forKey: .preconditionSteps)
        try container.encodeIfPresent(steps, forKey: .steps)
        try container.encodeIfPresent(postconditionSteps, forKey: .postconditionSteps)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

