//
// AutotestSelectModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AutotestSelectModel: Codable, JSONEncodable, Hashable {

    internal var filter: AutotestFilterModel
    internal var extractionModel: AutotestsExtractionModel

    internal init(filter: AutotestFilterModel, extractionModel: AutotestsExtractionModel) {
        self.filter = filter
        self.extractionModel = extractionModel
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case extractionModel
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filter, forKey: .filter)
        try container.encode(extractionModel, forKey: .extractionModel)
    }
}

