//
// AutotestHistoricalResultSelectModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct AutotestHistoricalResultSelectModel: Codable, JSONEncodable, Hashable {

    static let outcomesRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let testPlanIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let testRunIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let configurationIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let launchSourceRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    static let userIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    internal var outcomes: Set<AutotestResultOutcome>?
    internal var testPlanIds: Set<UUID>?
    internal var testRunIds: Set<UUID>?
    internal var configurationIds: Set<UUID>?
    internal var launchSource: String?
    internal var userIds: Set<UUID>?
    internal var duration: Int64RangeSelectorModel?

    internal init(outcomes: Set<AutotestResultOutcome>? = nil, testPlanIds: Set<UUID>? = nil, testRunIds: Set<UUID>? = nil, configurationIds: Set<UUID>? = nil, launchSource: String? = nil, userIds: Set<UUID>? = nil, duration: Int64RangeSelectorModel? = nil) {
        self.outcomes = outcomes
        self.testPlanIds = testPlanIds
        self.testRunIds = testRunIds
        self.configurationIds = configurationIds
        self.launchSource = launchSource
        self.userIds = userIds
        self.duration = duration
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case outcomes
        case testPlanIds
        case testRunIds
        case configurationIds
        case launchSource
        case userIds
        case duration
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(outcomes, forKey: .outcomes)
        try container.encodeIfPresent(testPlanIds, forKey: .testPlanIds)
        try container.encodeIfPresent(testRunIds, forKey: .testRunIds)
        try container.encodeIfPresent(configurationIds, forKey: .configurationIds)
        try container.encodeIfPresent(launchSource, forKey: .launchSource)
        try container.encodeIfPresent(userIds, forKey: .userIds)
        try container.encodeIfPresent(duration, forKey: .duration)
    }
}

