//
// BackgroundJobAttachmentModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct BackgroundJobAttachmentModel: Codable, JSONEncodable, Hashable {

    internal var id: UUID
    internal var name: String
    internal var type: String
    internal var size: Float

    internal init(id: UUID, name: String, type: String, size: Float) {
        self.id = id
        self.name = name
        self.type = type
        self.size = size
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case type
        case size
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encode(size, forKey: .size)
    }
}

