//
// BackgroundJobFilterModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct BackgroundJobFilterModel: Codable, JSONEncodable, Hashable {

    internal var types: [BackgroundJobType]?
    internal var states: [BackgroundJobState]?
    internal var isDeleted: Bool?
    internal var startDate: DateTimeRangeSelectorModel?
    internal var endDate: DateTimeRangeSelectorModel?

    internal init(types: [BackgroundJobType]? = nil, states: [BackgroundJobState]? = nil, isDeleted: Bool? = nil, startDate: DateTimeRangeSelectorModel? = nil, endDate: DateTimeRangeSelectorModel? = nil) {
        self.types = types
        self.states = states
        self.isDeleted = isDeleted
        self.startDate = startDate
        self.endDate = endDate
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case types
        case states
        case isDeleted
        case startDate
        case endDate
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(types, forKey: .types)
        try container.encodeIfPresent(states, forKey: .states)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
    }
}

