//
// ConfigurationByParametersModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ConfigurationByParametersModel: Codable, JSONEncodable, Hashable {

    static let parameterIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    /** This property is used to link configuration with project */
    internal var projectId: UUID
    internal var parameterIds: Set<UUID>

    internal init(projectId: UUID, parameterIds: Set<UUID>) {
        self.projectId = projectId
        self.parameterIds = parameterIds
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case projectId
        case parameterIds
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(parameterIds, forKey: .parameterIds)
    }
}

