//
// ConfigurationModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ConfigurationModel: Codable, JSONEncodable, Hashable {

    internal var description: String?
    internal var parameters: [String: String]?
    /** This property is used to link configuration with project */
    internal var projectId: UUID
    internal var isDefault: Bool
    internal var name: String?
    internal var createdDate: Date
    internal var modifiedDate: Date?
    internal var createdById: UUID
    internal var modifiedById: UUID?
    internal var globalId: Int64
    /** Unique ID of the entity */
    internal var id: UUID
    /** Indicates if the entity is deleted */
    internal var isDeleted: Bool

    internal init(description: String? = nil, parameters: [String: String]? = nil, projectId: UUID, isDefault: Bool, name: String? = nil, createdDate: Date, modifiedDate: Date? = nil, createdById: UUID, modifiedById: UUID? = nil, globalId: Int64, id: UUID, isDeleted: Bool) {
        self.description = description
        self.parameters = parameters
        self.projectId = projectId
        self.isDefault = isDefault
        self.name = name
        self.createdDate = createdDate
        self.modifiedDate = modifiedDate
        self.createdById = createdById
        self.modifiedById = modifiedById
        self.globalId = globalId
        self.id = id
        self.isDeleted = isDeleted
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case parameters
        case projectId
        case isDefault
        case name
        case createdDate
        case modifiedDate
        case createdById
        case modifiedById
        case globalId
        case id
        case isDeleted
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(parameters, forKey: .parameters)
        try container.encode(projectId, forKey: .projectId)
        try container.encode(isDefault, forKey: .isDefault)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(createdDate, forKey: .createdDate)
        try container.encodeIfPresent(modifiedDate, forKey: .modifiedDate)
        try container.encode(createdById, forKey: .createdById)
        try container.encodeIfPresent(modifiedById, forKey: .modifiedById)
        try container.encode(globalId, forKey: .globalId)
        try container.encode(id, forKey: .id)
        try container.encode(isDeleted, forKey: .isDeleted)
    }
}

