//
// CustomAttributeTemplatePutModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CustomAttributeTemplatePutModel: Codable, JSONEncodable, Hashable {

    static let customAttributeIdsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    static let nameRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    /** Unique ID of the attribute template */
    internal var id: UUID
    /** Collection of attribute IDs */
    internal var customAttributeIds: Set<UUID>?
    /** Custom attributes template name */
    internal var name: String

    internal init(id: UUID, customAttributeIds: Set<UUID>? = nil, name: String) {
        self.id = id
        self.customAttributeIds = customAttributeIds
        self.name = name
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case customAttributeIds
        case name
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(customAttributeIds, forKey: .customAttributeIds)
        try container.encode(name, forKey: .name)
    }
}

