//
// CustomAttributeOptionPostModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct CustomAttributeOptionPostModel: Codable, JSONEncodable, Hashable {

    static let valueRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    /** Value of the attribute option */
    internal var value: String?
    /** Indicates if the attribute option is used by default */
    internal var isDefault: Bool

    internal init(value: String? = nil, isDefault: Bool) {
        self.value = value
        self.isDefault = isDefault
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case isDefault
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encode(isDefault, forKey: .isDefault)
    }
}

