//
// DateTimeRangeSelectorModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct DateTimeRangeSelectorModel: Codable, JSONEncodable, Hashable {

    internal var from: Date?
    internal var to: Date?

    internal init(from: Date? = nil, to: Date? = nil) {
        self.from = from
        self.to = to
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case to
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(to, forKey: .to)
    }
}

