//
// GuidExtractionModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct GuidExtractionModel: Codable, JSONEncodable, Hashable {

    internal var include: [UUID]?
    internal var exclude: [UUID]?

    internal init(include: [UUID]? = nil, exclude: [UUID]? = nil) {
        self.include = include
        self.exclude = exclude
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case include
        case exclude
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(include, forKey: .include)
        try container.encodeIfPresent(exclude, forKey: .exclude)
    }
}

