//
// Int64ChangedFieldViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Int64ChangedFieldViewModel: Codable, JSONEncodable, Hashable {

    internal var oldValue: Int64
    internal var newValue: Int64

    internal init(oldValue: Int64, newValue: Int64) {
        self.oldValue = oldValue
        self.newValue = newValue
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case oldValue
        case newValue
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(oldValue, forKey: .oldValue)
        try container.encode(newValue, forKey: .newValue)
    }
}

