//
// LabelShortModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct LabelShortModel: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Global ID of the label */
    internal var globalId: Int64
    /** Name of the label */
    internal var name: String

    internal init(globalId: Int64, name: String) {
        self.globalId = globalId
        self.name = name
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case globalId
        case name
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(globalId, forKey: .globalId)
        try container.encode(name, forKey: .name)
    }
}

