//
// LinkType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal enum LinkType: String, Codable, CaseIterable {
    case related = "Related"
    case blockedBy = "BlockedBy"
    case defect = "Defect"
    case issue = "Issue"
    case requirement = "Requirement"
    case repository = "Repository"
}
