//
// NotificationModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct NotificationModel: Codable, JSONEncodable, Hashable {

    internal var id: UUID
    internal var createdDate: Date?
    internal var isRead: Bool
    internal var entityId: UUID
    internal var notificationType: NotificationTypeModel
    internal var projectGlobalId: Int64?
    internal var projectName: String?
    internal var testPlanGlobalId: Int64
    internal var testPlanName: String
    internal var workitemGlobalId: Int64?
    internal var comment: String
    internal var workItemName: String
    internal var attributeName: String?
    internal var createdById: UUID

    internal init(id: UUID, createdDate: Date? = nil, isRead: Bool, entityId: UUID, notificationType: NotificationTypeModel, projectGlobalId: Int64? = nil, projectName: String? = nil, testPlanGlobalId: Int64, testPlanName: String, workitemGlobalId: Int64? = nil, comment: String, workItemName: String, attributeName: String? = nil, createdById: UUID) {
        self.id = id
        self.createdDate = createdDate
        self.isRead = isRead
        self.entityId = entityId
        self.notificationType = notificationType
        self.projectGlobalId = projectGlobalId
        self.projectName = projectName
        self.testPlanGlobalId = testPlanGlobalId
        self.testPlanName = testPlanName
        self.workitemGlobalId = workitemGlobalId
        self.comment = comment
        self.workItemName = workItemName
        self.attributeName = attributeName
        self.createdById = createdById
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdDate
        case isRead
        case entityId
        case notificationType
        case projectGlobalId
        case projectName
        case testPlanGlobalId
        case testPlanName
        case workitemGlobalId
        case comment
        case workItemName
        case attributeName
        case createdById
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(createdDate, forKey: .createdDate)
        try container.encode(isRead, forKey: .isRead)
        try container.encode(entityId, forKey: .entityId)
        try container.encode(notificationType, forKey: .notificationType)
        try container.encodeIfPresent(projectGlobalId, forKey: .projectGlobalId)
        try container.encodeIfPresent(projectName, forKey: .projectName)
        try container.encode(testPlanGlobalId, forKey: .testPlanGlobalId)
        try container.encode(testPlanName, forKey: .testPlanName)
        try container.encodeIfPresent(workitemGlobalId, forKey: .workitemGlobalId)
        try container.encode(comment, forKey: .comment)
        try container.encode(workItemName, forKey: .workItemName)
        try container.encodeIfPresent(attributeName, forKey: .attributeName)
        try container.encode(createdById, forKey: .createdById)
    }
}

