//
// NotificationTypeModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal enum NotificationTypeModel: String, Codable, CaseIterable {
    case mentionInComment = "MentionInComment"
    case testPointIsSetInTestPlan = "TestPointIsSetInTestPlan"
    case mentionInCustomAttribute = "MentionInCustomAttribute"
    case testPlanUnlockRequest = "TestPlanUnlockRequest"
}
