//
// Operation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Operation: Codable, JSONEncodable, Hashable {

    internal var value: AnyCodable?
    internal var path: String?
    internal var op: String?
    internal var from: String?

    internal init(value: AnyCodable? = nil, path: String? = nil, op: String? = nil, from: String? = nil) {
        self.value = value
        self.path = path
        self.op = op
        self.from = from
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case path
        case op
        case from
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(op, forKey: .op)
        try container.encodeIfPresent(from, forKey: .from)
    }
}

