//
// ParameterFilterModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ParameterFilterModel: Codable, JSONEncodable, Hashable {

    /** Specifies a parameter deleted status to search for */
    internal var isDeleted: Bool?
    /** Specifies a parameter key name to search for */
    internal var name: String?

    internal init(isDeleted: Bool? = nil, name: String? = nil) {
        self.isDeleted = isDeleted
        self.name = name
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case isDeleted
        case name
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isDeleted, forKey: .isDeleted)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

