//
// ProjectPostModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct ProjectPostModel: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** Description of the project */
    internal var description: String?
    /** Name of the project */
    internal var name: String
    /** Indicates if the project is marked as favorite */
    internal var isFavorite: Bool?
    /** Indicates if the status \"Flaky/Stable\" sets automatically */
    internal var isFlakyAuto: Bool?

    internal init(description: String? = nil, name: String, isFavorite: Bool? = nil, isFlakyAuto: Bool? = nil) {
        self.description = description
        self.name = name
        self.isFavorite = isFavorite
        self.isFlakyAuto = isFlakyAuto
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case name
        case isFavorite
        case isFlakyAuto
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(isFavorite, forKey: .isFavorite)
        try container.encodeIfPresent(isFlakyAuto, forKey: .isFlakyAuto)
    }
}

