//
// SearchCustomAttributeTemplateGetModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct SearchCustomAttributeTemplateGetModel: Codable, JSONEncodable, Hashable {

    internal var id: UUID
    internal var isDeleted: Bool
    internal var name: String
    internal var projectShortestModels: [ProjectShortestModel]
    internal var customAttributeModels: [CustomAttributeModel]

    internal init(id: UUID, isDeleted: Bool, name: String, projectShortestModels: [ProjectShortestModel], customAttributeModels: [CustomAttributeModel]) {
        self.id = id
        self.isDeleted = isDeleted
        self.name = name
        self.projectShortestModels = projectShortestModels
        self.customAttributeModels = customAttributeModels
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case isDeleted
        case name
        case projectShortestModels
        case customAttributeModels
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(isDeleted, forKey: .isDeleted)
        try container.encode(name, forKey: .name)
        try container.encode(projectShortestModels, forKey: .projectShortestModels)
        try container.encode(customAttributeModels, forKey: .customAttributeModels)
    }
}

