//
// TestSuiteChangeViewModelChangedFieldViewModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct TestSuiteChangeViewModelChangedFieldViewModel: Codable, JSONEncodable, Hashable {

    internal var oldValue: TestSuiteChangeViewModel?
    internal var newValue: TestSuiteChangeViewModel?

    internal init(oldValue: TestSuiteChangeViewModel? = nil, newValue: TestSuiteChangeViewModel? = nil) {
        self.oldValue = oldValue
        self.newValue = newValue
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case oldValue
        case newValue
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(oldValue, forKey: .oldValue)
        try container.encodeIfPresent(newValue, forKey: .newValue)
    }
}

