//
// TestPlanGroupByTester.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct TestPlanGroupByTester: Codable, JSONEncodable, Hashable {

    internal var userId: UUID?
    internal var value: Int64

    internal init(userId: UUID? = nil, value: Int64) {
        self.userId = userId
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case userId
        case value
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encode(value, forKey: .value)
    }
}

