//
// TestSuiteV2TreeModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct TestSuiteV2TreeModel: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    /** nested enumeration of children is allowed */
    @available(*, deprecated, message: "This property is deprecated.")
    internal var children: [TestSuiteV2TreeModel]?
    /** Unique ID of the test suite */
    internal var id: UUID
    /** Date of the last refresh of the test suite */
    internal var refreshDate: Date?
    /** Unique ID of the parent test suite in hierarchy */
    internal var parentId: UUID?
    /** Unique ID of test plan to which the test suite belongs */
    internal var testPlanId: UUID
    /** Name of the test suite */
    internal var name: String
    /** Type of the test suite */
    internal var type: TestSuiteType?
    /** Indicates if the test suite retains section tree structure */
    internal var saveStructure: Bool?
    /** Indicates if scheduled auto refresh is enabled for the test suite */
    internal var autoRefresh: Bool?

    internal init(children: [TestSuiteV2TreeModel]? = nil, id: UUID, refreshDate: Date? = nil, parentId: UUID? = nil, testPlanId: UUID, name: String, type: TestSuiteType? = nil, saveStructure: Bool? = nil, autoRefresh: Bool? = nil) {
        self.children = children
        self.id = id
        self.refreshDate = refreshDate
        self.parentId = parentId
        self.testPlanId = testPlanId
        self.name = name
        self.type = type
        self.saveStructure = saveStructure
        self.autoRefresh = autoRefresh
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case children
        case id
        case refreshDate
        case parentId
        case testPlanId
        case name
        case type
        case saveStructure
        case autoRefresh
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(refreshDate, forKey: .refreshDate)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(testPlanId, forKey: .testPlanId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(saveStructure, forKey: .saveStructure)
        try container.encodeIfPresent(autoRefresh, forKey: .autoRefresh)
    }
}

