//
// TestPlanGroupByStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct TestPlanGroupByStatus: Codable, JSONEncodable, Hashable {

    internal var status: String
    internal var value: Int64

    internal init(status: String, value: Int64) {
        self.status = status
        self.value = value
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case value
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(value, forKey: .value)
    }
}

