//
// TestResultOutcome.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal enum TestResultOutcome: String, Codable, CaseIterable {
    case inProgress = "InProgress"
    case passed = "Passed"
    case failed = "Failed"
    case skipped = "Skipped"
    case blocked = "Blocked"
}
