//
// WorkItemSelectModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Model containing options to filter work items */
internal struct WorkItemSelectModel: Codable, JSONEncodable, Hashable {

    /** Collection of filters to apply to search */
    internal var filter: WorkItemFilterModel
    /** Rules for different level entities inclusion/exclusion */
    internal var extractionModel: WorkItemExtractionModel?

    internal init(filter: WorkItemFilterModel, extractionModel: WorkItemExtractionModel? = nil) {
        self.filter = filter
        self.extractionModel = extractionModel
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case extractionModel
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(filter, forKey: .filter)
        try container.encodeIfPresent(extractionModel, forKey: .extractionModel)
    }
}

