//
// WorkItemMovePostModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct WorkItemMovePostModel: Codable, JSONEncodable, Hashable {

    internal var id: UUID
    internal var newSectionId: UUID
    internal var oldSectionId: UUID?
    internal var nextWorkItemId: UUID?

    internal init(id: UUID, newSectionId: UUID, oldSectionId: UUID? = nil, nextWorkItemId: UUID? = nil) {
        self.id = id
        self.newSectionId = newSectionId
        self.oldSectionId = oldSectionId
        self.nextWorkItemId = nextWorkItemId
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case newSectionId
        case oldSectionId
        case nextWorkItemId
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(newSectionId, forKey: .newSectionId)
        try container.encodeIfPresent(oldSectionId, forKey: .oldSectionId)
        try container.encodeIfPresent(nextWorkItemId, forKey: .nextWorkItemId)
    }
}

