//
// WorkItemState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal enum WorkItemState: String, Codable, CaseIterable {
    case needsWork = "NeedsWork"
    case notReady = "NotReady"
    case ready = "Ready"
}
